name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.25
          cache: true

      - name: Create .env file
        run: |
          cat << EOF > .env
          ${{ secrets.DATABASE_ENV }}
          EOF
        shell: bash

      - name: Install dependencies
        run: go mod tidy

      - name: Start services with Docker Compose
        run: docker compose up -d

      - name: Wait for database to be ready
        run: |
            docker compose ps
            sleep 5
    
      - name: Install golang-migrate CLI
        run: |
          go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          which migrate

      - name: Echo DB_URL
        run: echo $DB_URL

      - name: Run database migrations
        run: |
          migrate -path internal/db/migrations -database $DB_URL -verbose up 1

      - name: Run tests
        run: go test ./...
